version: '2'
services:
  nagios:
    image: nagios
    command: --enable-ndo --create-db --server-url http://192.168.120.236
    ports:
      - 80:80
      - 4000:3000
    restart: always
    networks:
      - nagios-network
    depends_on:
      - nagios_mysql
    volumes:
      - ./data/plugin:/data/plugin
      - ./data/conf:/usr/local/nagios/etc/mount
      - ./data/example:/data/example

  nagios_mysql:
    image: mysql:5.6
    ports:
      - 3306:3306
    restart: always
    networks:
      - nagios-network
    environment:
      - MYSQL_USER=nagios
      - MYSQL_PASSWORD=nagios
      - MYSQL_ADDRESS=nagios_mysql
      - MYSQL_DATABASE=nagios
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

networks:
  nagios-network:
    driver: bridge
